# Generated by Django 5.0.2 on 2024-02-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(default='unknown', max_length=8, unique=True)),
                ('artist', models.TextField(default='unknown', max_length=240)),
                ('source_type', models.CharField(default='unknown', max_length=10)),
                ('source_path', models.TextField(default='unknown', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(default='unknown', max_length=8, unique=True)),
                ('name', models.CharField(default='unknown', max_length=8, unique=True)),
                ('description', models.TextField(default='unknown', max_length=500, unique=True)),
                ('songs', models.ManyToManyField(to='api.songs')),
            ],
        ),
    ]
